apiVersion: batch/v1
kind: Job
metadata:
  # Random characters added to the end of the job name because jobs cannot be
  # updated.
  name: {{ include "mw.fullname" . }}-init-db-x{{ randAlphaNum 8 | lower }}x
spec:
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: ca
          configMap:
            name: kube-root-ca.crt
        - name: l10n
          hostPath:
            path: {{ .Values.l10n.cache.nodePath }}
            type: DirectoryOrCreate
        - name: private
          secret:
            secretName: {{ include "mw.fullname" . }}-private
      containers:
        - name: {{ .Chart.Name }}-init-db
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/init-db.sh" ]
          env:
            - name: DB_SERVER
              value: mw-db  # FIXME: This should be autogenerated
            - name: DB_USER
              value: {{ .Values.db.db.user | quote }}
            # FIXME: Should be in a Secret
            - name: DB_PASS
              value: {{ .Values.db.db.password | quote }}
            - name: INIT_L10N_LANGS
              value: {{ .Values.l10n.cache.langs | join "," | quote }}
            - name: INIT_L10N_THREADS
              value: {{ .Values.l10n.cache.rebuildThreads | quote }}
            - name: INIT_L10N_CACHE_DIR
              value: {{ .Values.l10n.cache.containerPath | quote }}
          volumeMounts:
            - name: ca
              mountPath: /usr/local/share/ca-certificates
              readOnly: true
            - name: l10n
              mountPath: {{ .Values.l10n.cache.containerPath }}
            - name: private
              mountPath: /srv/mediawiki/private
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
