apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mw.fullname" . }}-private
  labels:
{{ include "mw.labels" . | indent 4 }}
data:
  PrivateSettings.php: {{ .Files.Get "files/PrivateSettings.php"  | b64enc }} 
