#!/bin/bash

set -eu -o pipefail

# This operation takes about 5 minutes for 2 MW versions.

WIKIVERSIONS=wikiversions-dev.json
BUILD_DIR=/srv/mediawiki

for tool in jq git sort; do
    if ! command -v $tool >/dev/null; then
        echo "Please install '$tool'"
        exit 1
    fi
done

function unique_wikiversions {
    jq -r 'values[]' $WIKIVERSIONS | sort -u
}

function prep_version {
    local vers=$1               # vers will be something like php-1.36.0-wmf.27

    local nophpvers=${vers:4}   # will be something like 1.36.0-wmf.27
    local branch=wmf/$nophpvers # branch will be something like wmf/1.36.0-wmf.27

    # https://gerrit.wikimedia.org/r
    time git clone --depth 1 -b $branch https://gerrit.wikimedia.org/r/mediawiki/core $vers
    git -C $vers config submodule.fetchJobs $(getconf _NPROCESSORS_ONLN)
    time git -C $vers submodule update --init --recursive

    cat <<EOF > $vers/LocalSettings.php
<?php
require __DIR__ . "/../wmf-config/CommonSettings.php";
EOF
}    


function checkout_mediawiki_config {
    time git clone --depth 1 -b dancy-k8s-dev https://gerrit.wikimedia.org/r/operations/mediawiki-config $BUILD_DIR
}

# Writes to stdout
function generate_wikiversions_php {
    cat <<EOF
<?php
return array(
EOF
    jq -r 'to_entries[] | "    \"\(.key)\" => \"\(.value)\","' < $WIKIVERSIONS
    cat <<EOF
);
EOF
}

function compile_wikiversions {
    php=$(basename $WIKIVERSIONS .json).php
    
    generate_wikiversions_php > $php
}

# Start fresh
rm -fr $BUILD_DIR

checkout_mediawiki_config

cd $BUILD_DIR

compile_wikiversions

for vers in $(unique_wikiversions); do
    prep_version $vers
done

find $BUILD_DIR -name .git | xargs rm -fr

echo Image storage requirements
du $BUILD_DIR -s -h
