{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "etcd.serviceAccountName" . }}
  labels:
{{ include "etcd.labels" . | indent 4 }}
{{- end -}}
